"""Submission generated by cat_benchmark.py on 11th September, 2020
"""

import os
import pandas as pd

COMPETITION_NAME = 'competitive-data-science-predict-future-sales'

SUBMISSION_DIR = '.'
SUBMISSION_FILE = 'sub_cat_benchmark_0911_1431_cat_baseline.csv'
SUBMISSION_MESSAGE = "\"Benchamrk with CatBoost. item_cnt_month clipped between o to 20, validation on last month of training data (33). Final model is built using month upto 32 and final prediction is done on test data using that model.\""

df = pd.read_csv(f'{SUBMISSION_DIR}/{SUBMISSION_FILE}')
print(df.head())

submission_string = f"kaggle competitions submit {COMPETITION_NAME} -f {SUBMISSION_DIR}/{SUBMISSION_FILE} -m {SUBMISSION_MESSAGE}"

print(submission_string)

os.system(submission_string)
