"""Submission generated by xbg_benchmark.py on 7th September, 2020
"""

import os
import pandas as pd

COMPETITION_NAME = 'competitive-data-science-predict-future-sales'

SUBMISSION_DIR = '.'
SUBMISSION_FILE = 'sub_xgb_benchmark_0907_1129_xgb_baseline.csv'
SUBMISSION_MESSAGE = "\"Benchamrk with XGB item_cnt_month clipped between o to 20, validation on month before prediction (33)\""

df = pd.read_csv(f'{SUBMISSION_DIR}/{SUBMISSION_FILE}')
print(df.head())

submission_string = f"kaggle competitions submit {COMPETITION_NAME} -f {SUBMISSION_DIR}/{SUBMISSION_FILE} -m {SUBMISSION_MESSAGE}"

print(submission_string)

os.system(submission_string)
